### PR TITLE
Added youtube-dl

### PR DESCRIPTION
**Pull request by ChrisLeeGit**

### CODE REVIEW

**Comment by VoLuong** [comment]
hmm @ChrisLeeGit  can you help translate the description in the readme cn version :D if yes thank youuu and i ll merge right away

**Comment by ChrisLeeGit** [comment]
@VoLuong No problem, I just added the Chinese description for youtube-dl in the README_cn file.

**Comment by VoLuong** [comment]
Xièxiè @ChrisLeeGit

**Comment by ChrisLeeGit** [comment]
My pleasure.

**Pull request merged**
