### PR TITLE
Added Adapta, Compton, Rhythmbox, Arc Icon Theme, Paper Icon Theme

### PR DESCRIPTION
**Pull request by stelariusinfinitek**

### CODE REVIEW

**Comment by VoLuong** [comment]
Would you consider moving compton to Windows manager section ?

**Comment by stelariusinfinitek** [comment]
Sorry, I think I missed that. Sure will do.

**Comment by stelariusinfinitek** [comment]
I don't see a section with Composite managers. I saw compiz and I added it there. Should I create a new section with Composite managers?

**Comment by VoLuong** [comment]
image
Can this section help :-? Because I read somewhere they wrote like "Compton is a standalone composite manager, suitable for use with window managers that do not natively provide compositing functionality. "
If that section is not clear enough, you are welcomed to create a section for that :wink:

**Comment by stelariusinfinitek** [comment]
I hope it's better now. :)

**Comment by VoLuong** [comment]
Thank you :love_letter:

**Pull request merged**
